<?php

namespace Database\Seeders;

use App\Models\CarModel;
use App\Models\Make;
use Illuminate\Database\Seeder;

class MakeModelSeeder2 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //toyota
        $toyota_make = Make::where('name', 'LIKE', '%Toyota%')->first();
        foreach ([
                     "4runner",
                     "86",
                     "allex",
                     "allion",
                     "alphard",
                     "alphard hybrid",
                     "altezza",
                     "altezza gita",
                     "aqua",
                     "aristo",
                     "auris",
                     "avalon",
                     "avensis",
                     "avensis wagon",
                     "bb",
                     "belta",
                     "blade",
                     "blizzard",
                     "brevis",
                     "bz4x",
                     "c-hr",
                     "caldina",
                     "cami",
                     "camroad",
                     "camry",
                     "camry gracia wagon",
                     "carina",
                     "carina ed",
                     "carina surf",
                     "celica",
                     "celsior",
                     "century",
                     "chaser",
                     "classic",
                     "coaster",
                     "corolla",
                     "corolla altis",
                     "corolla axio",
                     "corolla cross",
                     "corolla fielder",
                     "corolla ii",
                     "corolla levin",
                     "corolla rumion",
                     "corolla runx",
                     "corolla spacio",
                     "corolla sport",
                     "corolla touring",
                     "corolla van",
                     "corolla wagon",
                     "corona",
                     "corona premio",
                     "corsa",
                     "cresta",
                     "crown",
                     "crown comfort",
                     "crown crossover",
                     "crown estate",
                     "crown hybrid",
                     "crown majesta",
                     "crown stationwagon",
                     "crown van",
                     "curren",
                     "cynos",
                     "duet",
                     "dyna",
                     "dyna hybrid",
                     "dyna routevan",
                     "esquire",
                     "estima",
                     "estima emina",
                     "estima hybrid",
                     "estima lucida",
                     "fj cruiser",
                     "fortuner",
                     "funcargo",
                     "gaia",
                     "granace",
                     "grand hiace",
                     "granvia",
                     "harrier",
                     "harrier hybrid",
                     "hiace commuter",
                     "hiace regius",
                     "hiace truck",
                     "hiace van",
                     "hiace wagon",
                     "highlander",
                     "hilux",
                     "hilux revo",
                     "hilux surf",
                     "hilux vigo",
                     "innova",
                     "ipsum",
                     "iq",
                     "isis",
                     "ist",
                     "kluger",
                     "kluger hybrid",
                     "land cruiser",
                     "land cruiser 100",
                     "land cruiser 60",
                     "land cruiser 70",
                     "land cruiser 80",
                     "land cruiser prado",
                     "liteace",
                     "liteace noah",
                     "liteace truck",
                     "liteace van",
                     "majesty",
                     "mark ii",
                     "mark ii blit",
                     "mark ii qualis",
                     "mark ii van",
                     "mark ii wagon",
                     "mark x",
                     "mark x zio",
                     "master ace surf",
                     "mega cruiser",
                     "mirai",
                     "mr2",
                     "mrs",
                     "nadia",
                     "noah",
                     "opa",
                     "origin",
                     "passo",
                     "passo sette",
                     "pixis epoch",
                     "pixis joy",
                     "pixis mega",
                     "pixis space",
                     "pixis van",
                     "platz",
                     "porte",
                     "premio",
                     "previa",
                     "prius",
                     "prius alpha",
                     "prius phv",
                     "proace",
                     "probox van",
                     "probox van hybrid",
                     "probox wagon",
                     "progres",
                     "pronard",
                     "ractis",
                     "raize",
                     "raum",
                     "rav4",
                     "rav4 phv",
                     "regius",
                     "regius ace van",
                     "regiusace commuter",
                     "regiusace van",
                     "roomy",
                     "rush",
                     "sai",
                     "scepter stationwagon",
                     "sequoia",
                     "sera",
                     "sienta",
                     "soarer",
                     "spade",
                     "sparky",
                     "sprinter",
                     "sprinter carib",
                     "sprinter marino",
                     "sprinter trueno",
                     "sprinter van",
                     "starlet",
                     "succeed van",
                     "succeed van hybrid",
                     "succeed wagon",
                     "supra",
                     "tacoma",
                     "tank",
                     "tercel",
                     "touring hiace",
                     "townace",
                     "townace noah",
                     "townace truck",
                     "townace van",
                     "townace wagon",
                     "toyoace",
                     "toyoace route van",
                     "toyoace truck",
                     "toyota",
                     "toyota(other)",
                     "tundra",
                     "vanguard",
                     "vellfire",
                     "vellfire hybrid",
                     "verossa",
                     "vios",
                     "vista",
                     "vista ardeo",
                     "vitz",
                     "voltz",
                     "voxy",
                     "will cypha",
                     "will vi",
                     "will vs",
                     "windom",
                     "wish",
                     "yaris",
                     "yaris cross",
                     "yaris verso",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $toyota_make->id, 'name' => ucfirst($model_name) ]);
        }

        //suzuki
        $suzuki_make = Make::create(['name' => 'Suzuki']);
        foreach ([
                    "aerio sedan",
                    "alto",
                    "alto eco",
                    "alto lapin",
                    "baleno",
                    "cappuccino",
                    "cara",
                    "carry truck",
                    "chevrolet cruze",
                    "cultus",
                    "escudo",
                    "every",
                    "every wagon",
                    "grand escudo",
                    "grand vitara",
                    "hustler",
                    "ignis",
                    "jimny",
                    "jimny sierra",
                    "jimny wide",
                    "kei",
                    "kizashi",
                    "landy",
                    "mr wagon",
                    "palette",
                    "solio",
                    "solio bandit",
                    "spacia",
                    "splash",
                    "swift",
                    "swift sport",
                    "sx4",
                    "sx4 s cross",
                    "sx4 sedan",
                    "twin",
                    "vitara",
                    "wagon r",
                    "wagon r wide",
                    "x90",
                    "xbee",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $suzuki_make->id, 'name' => ucfirst($model_name) ]);
        }

        //nissan
        $nissan_make = Make::where('name', 'LIKE', '%Nissan%')->first();
        foreach ([
                    "180sx",
                    "350z",
                    "ad",
                    "ad expert",
                    "ad max wagon",
                    "ad van",
                    "altima",
                    "ariya",
                    "armada",
                    "atlas truck",
                    "aura",
                    "avenir",
                    "avenir cargo",
                    "bassara",
                    "be-1",
                    "bluebird",
                    "bluebird sylphy",
                    "cabstar",
                    "caravan",
                    "caravan bus",
                    "caravan coach",
                    "cedric",
                    "cedric van",
                    "cedric wagon",
                    "cefiro",
                    "cefiro wagon",
                    "cima",
                    "civilian",
                    "clipper rio",
                    "clipper truck",
                    "clipper van",
                    "condor",
                    "crew",
                    "cube",
                    "cube cubic",
                    "datsun",
                    "datsun truck",
                    "dayz",
                    "dayz roox",
                    "dualis",
                    "elgrand",
                    "env200wagon",
                    "fairlady z",
                    "figaro",
                    "fuga",
                    "fuga hybrid",
                    "gloria",
                    "gloria van",
                    "gloria wagon",
                    "gt-r",
                    "homy",
                    "homy coach",
                    "homy van",
                    "infiniti q45",
                    "juke",
                    "kicks",
                    "kix",
                    "lafesta",
                    "largo",
                    "latio",
                    "laurel",
                    "leaf",
                    "leopard",
                    "leopard jferrie",
                    "liberty",
                    "lucino",
                    "march",
                    "march box",
                    "maxima",
                    "micra cc",
                    "mistral",
                    "murano",
                    "navara",
                    "nissan",
                    "nissan ud",
                    "note",
                    "nt100clipper",
                    "nt450atlas",
                    "nv100clipper",
                    "nv150 ad",
                    "nv200 wagon",
                    "nv200vanette van",
                    "nv200vanette wagon",
                    "nv350caravan",
                    "nv350caravan microbus",
                    "nv350caravan wagon",
                    "otti",
                    "pao",
                    "pathfinder",
                    "patrol",
                    "presage",
                    "presea",
                    "president",
                    "president js",
                    "primera",
                    "primera camino",
                    "primera camino wagon",
                    "primera wagon",
                    "pulsar",
                    "pulsar serie",
                    "pulsar serie srv",
                    "qashqai",
                    "qashqai+2",
                    "quon",
                    "rasheen",
                    "rnessa",
                    "rogue",
                    "roox",
                    "safari",
                    "sakura",
                    "serena",
                    "serena cargo",
                    "silvia",
                    "skyline",
                    "skyline crossover",
                    "stagea",
                    "sunny",
                    "sunny california",
                    "sunny truck",
                    "sylphy",
                    "sylphy ev",
                    "teana",
                    "terrano",
                    "terrano regulus",
                    "tiida",
                    "tiida latio",
                    "tino",
                    "urvan",
                    "vanette",
                    "vanette truck",
                    "vanette van",
                    "wingroad",
                    "xterra",
                    "xtrail",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $nissan_make->id, 'name' => ucfirst($model_name) ]);
        }

        //honda
        $honda_make = Make::where('name', 'LIKE', '%Honda%')->first();
        foreach ([
                    "accord",
                    "accord coupe",
                    "accord hybrid",
                    "accord tourer",
                    "accord wagon",
                    "acty truck",
                    "acty van",
                    "airwave",
                    "avancier",
                    "beat",
                    "capa",
                    "city",
                    "civic",
                    "civic coupe",
                    "civic ferio",
                    "civic hybrid",
                    "civic shuttle",
                    "clarity phev",
                    "cross road",
                    "crv",
                    "crv hybrid",
                    "crx",
                    "crx delsol",
                    "crz",
                    "domani",
                    "edix",
                    "element",
                    "elysion",
                    "elysion prestige",
                    "fit",
                    "fit aria",
                    "fit hybrid",
                    "fit shuttle",
                    "fit shuttle hybrid",
                    "freed",
                    "freed hybrid",
                    "freed spike",
                    "freed spike hybrid",
                    "freed+",
                    "freed+ hybrid",
                    "grace",
                    "honda-e",
                    "hr-v",
                    "insight",
                    "insight exclusive",
                    "inspire",
                    "integra",
                    "integra sj",
                    "jade",
                    "jazz",
                    "lagreat",
                    "legend",
                    "life",
                    "logo",
                    "mdx",
                    "mobilio",
                    "mobilio spike",
                    "n box",
                    "n box plus",
                    "nsx",
                    "nwgn",
                    "nwgn custom",
                    "odyssey",
                    "orthia",
                    "partner",
                    "prelude",
                    "s2000",
                    "saber",
                    "shuttle",
                    "smx",
                    "stepwagon",
                    "stepwagon spada",
                    "stream",
                    "street",
                    "thats",
                    "today",
                    "torneo",
                    "vamos",
                    "vezel",
                    "vigor",
                    "z",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $honda_make->id, 'name' => ucfirst($model_name) ]);
        }

        //daihatsu
        $daihatsu_make = Make::create(['name' => 'Daihatsu']);
        foreach ([
                    "altis",
                    "atrai",
                    "atrai wagon",
                    "bego",
                    "boon",
                    "boon luminas",
                    "cast",
                    "charade",
                    "coo",
                    "copen",
                    "delta truck",
                    "hijet cargo",
                    "hijet deckvan",
                    "hijet grancargo",
                    "hijet truck",
                    "hijet van",
                    "mira",
                    "mira cocoa",
                    "mira es",
                    "mira gino",
                    "mira gino 1000",
                    "move",
                    "pyzar",
                    "rocky",
                    "sonica",
                    "taft",
                    "tanto",
                    "terios",
                    "terios kid",
                    "thor",
                    "wake",
                    "yrv",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $daihatsu_make->id, 'name' => ucfirst($model_name) ]);
        }

        //mazda
        $mazda_make = Make::where('name', 'LIKE', '%Mazda%')->first();
        foreach ([
                    "atenza",
                    "atenza sedan",
                    "atenza sport",
                    "atenza sport wagon",
                    "atenza wagon",
                    "axela",
                    "axela hybrid",
                    "axela sport",
                    "az-1",
                    "azoffroad",
                    "biante",
                    "bongo",
                    "bongo friendee",
                    "bongo truck",
                    "bongo van",
                    "bongo wagon",
                    "bt-50",
                    "capella c2",
                    "capella wagon",
                    "carol",
                    "cx-30",
                    "cx-60",
                    "cx-9",
                    "cx3",
                    "cx5",
                    "cx7",
                    "cx8",
                    "demio",
                    "efini rx7",
                    "familia",
                    "familia s wagon",
                    "familia van",
                    "familia wagon",
                    "flair",
                    "lantis",
                    "laputa",
                    "luce",
                    "mazda",
                    "mazda2",
                    "mazda3",
                    "mazda3 fastback",
                    "mazda6",
                    "mazda6 wagon",
                    "mazda8",
                    "millenia",
                    "mpv",
                    "mx-30",
                    "mx-30ev",
                    "mx-5",
                    "porter cab truck",
                    "premacy",
                    "proceed",
                    "proceed marvie",
                    "revue",
                    "roadster",
                    "rx7",
                    "rx8",
                    "savanna rx7",
                    "scrum",
                    "scrum truck",
                    "scrum van",
                    "scrum wagon",
                    "sentia",
                    "titan",
                    "tribute",
                    "verisa",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $mazda_make->id, 'name' => ucfirst($model_name) ]);
        }

        //subaru
        $subaru_make = Make::where('name', 'LIKE', '%Subaru%')->first();
        foreach ([
                    "alcyone svx",
                    "brz",
                    "chiffon",
                    "dex",
                    "dias wagon",
                    "domingo",
                    "exiga",
                    "exiga crossover 7",
                    "forester",
                    "impreza",
                    "impreza anesis",
                    "impreza g4",
                    "impreza sport",
                    "impreza sport hybrid",
                    "impreza sports wagon",
                    "impreza xv",
                    "justy",
                    "legacy",
                    "legacy b4",
                    "legacy lancaster",
                    "legacy outback",
                    "legacy touring wagon",
                    "levorg",
                    "lucra",
                    "outback",
                    "pleo",
                    "pleo plus",
                    "sambar",
                    "sambar dias",
                    "sambar truck",
                    "stella",
                    "traviq",
                    "trezia",
                    "vivio",
                    "wrx",
                    "wrx s4",
                    "wrx sti",
                    "xv",
                    "xv hybrid",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $subaru_make->id, 'name' => ucfirst($model_name) ]);
        }

        //mitsubishi
        $mitsubishi_make = Make::where('name', 'LIKE', '%Mitsubishi%')->first();
        foreach ([
                    "aero midi",
                    "airtrek",
                    "asx",
                    "canter guts",
                    "canter truck",
                    "challenger",
                    "chariot",
                    "chariot grandis",
                    "colt",
                    "colt plus",
                    "debonair",
                    "delica cargo",
                    "delica d2",
                    "delica d3",
                    "delica d5",
                    "delica mini",
                    "delica space gear",
                    "delica star wagon",
                    "delica truck",
                    "delica van",
                    "diamante",
                    "diamante wagon",
                    "dingo",
                    "dion",
                    "eclipse",
                    "eclipse cross",
                    "eclipse spider",
                    "ek cross",
                    "ek custom",
                    "ek space",
                    "ek space custom",
                    "ek sport",
                    "ek wagon",
                    "eterna",
                    "fighter",
                    "fto",
                    "galant",
                    "galant fortis",
                    "galant fortis sportback",
                    "grandis",
                    "great",
                    "gto",
                    "imiev",
                    "jeep",
                    "l200",
                    "lancer",
                    "lancer cargo",
                    "lancer cedia",
                    "lancer cedia wagon",
                    "lancer van",
                    "lancer wagon",
                    "legnum",
                    "minicab miev",
                    "minicab miev truck",
                    "minicab truck",
                    "minicab van",
                    "mirage",
                    "mirage asti",
                    "monterosport",
                    "outlander",
                    "outlander phev",
                    "pajero",
                    "pajero io",
                    "pajero jr",
                    "pajero mini",
                    "pajero sport",
                    "proudia",
                    "rosa",
                    "rvr",
                    "shogun",
                    "starion",
                    "strada",
                    "super great",
                    "toppo",
                    "town box",
                    "triton",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $mitsubishi_make->id, 'name' => ucfirst($model_name) ]);
        }

        //bmw
        $bmw_make = Make::where('name', 'LIKE', '%BMW%')->first();
        foreach ([
                    "1 series",
                    "4 series",
                    "5 series",
                    "5 series gran turismo",
                    "6 series",
                    "7 series",
                    "8 series",
                    "bmw",
                    "i3",
                    "i8",
                    "ix3",
                    "m coupe",
                    "m2",
                    "m3",
                    "m4",
                    "m5",
                    "m6",
                    "m8",
                    "mini",
                    "x1",
                    "x2",
                    "x3m",
                    "x4",
                    "x4m",
                    "x5m",
                    "x6",
                    "x6m",
                    "x7",
                    "xm",
                    "z3",
                    "z4",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $bmw_make->id, 'name' => ucfirst($model_name) ]);
        }

        //volkswagen
        $volkswagen_make = Make::where('name', 'LIKE', '%VOLKSWAGEN%')->first();
        foreach ([
                    "amarok",
                    "arteon",
                    "beetle",
                    "bora",
                    "caddy",
                    "cc",
                    "cross golf",
                    "eos",
                    "golf",
                    "golf alltrack",
                    "golf cabrio",
                    "golf cabriolet",
                    "golf gte",
                    "golf gti",
                    "golf plus",
                    "golf r",
                    "golf r variant",
                    "golf touran",
                    "golf variant",
                    "golf wagon",
                    "id.4 crozz",
                    "id.6 crozz",
                    "id.6x",
                    "jetta",
                    "lavida",
                    "lupo",
                    "magotan",
                    "new beetle",
                    "new beetle cabriolet",
                    "passat",
                    "passat alltrack",
                    "passat cc",
                    "passat gte variant",
                    "passat variant",
                    "passat variant 1",
                    "passat wagon",
                    "polo",
                    "polo gti",
                    "scirocco",
                    "sharan",
                    "t-cross",
                    "t-roc",
                    "the beetle",
                    "the beetle cabriolet",
                    "tiguan",
                    "touareg",
                    "touran",
                    "up",
                    "vanagon",
                    "volkswagen",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $volkswagen_make->id, 'name' => ucfirst($model_name) ]);
        }

        //audi
        $audi_make = Make::where('name', 'LIKE', '%Audi%')->first();
        foreach ([
                    "a1",
                    "a1 sportback",
                    "a2",
                    "a3",
                    "a3 sedan",
                    "a4",
                    "a4 allroad quattro",
                    "a4 avant",
                    "a4 cabriolet",
                    "a5",
                    "a5 cabriolet",
                    "a5 sportback",
                    "a6",
                    "a6 allroad quattro",
                    "a6 avant",
                    "a7",
                    "a7 sportback",
                    "a8",
                    "allroad quattro",
                    "audi",
                    "cabriolet",
                    "q2",
                    "q3",
                    "q5",
                    "q7",
                    "q8",
                    "r8",
                    "r8 spyder",
                    "rs q3",
                    "rs3",
                    "rs3 sportback",
                    "rs4",
                    "rs4 avant",
                    "rs5",
                    "rs5 cabriolet",
                    "rs6",
                    "rs6 avant",
                    "rs7 sportback",
                    "s1",
                    "s1 sportback",
                    "s3",
                    "s3 sedan",
                    "s4",
                    "s4 avant",
                    "s5",
                    "s5 cabriolet",
                    "s5 sportback",
                    "s6",
                    "s6 avant",
                    "s7 sportback",
                    "s8",
                    "s8 plus",
                    "sq2",
                    "sq5",
                    "tt coupe",
                    "tt roadster",
                    "tt rs coupe",
                    "tt rs plus coupe",
                    "tt rs roadster",
                    "tts coupe",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $audi_make->id, 'name' => ucfirst($model_name) ]);
        }

        //volvo
        $volvo_make = Make::where('name', 'LIKE', '%Volvo%')->first();
        foreach ([
                    "240",
                    "240 wagon",
                    "760",
                    "850",
                    "940",
                    "940 estate",
                    "960",
                    "c30",
                    "c70",
                    "cross country",
                    "fh",
                    "fh12",
                    "fm",
                    "fm12",
                    "s40",
                    "s60",
                    "s70",
                    "s80",
                    "s90",
                    "v40",
                    "v50",
                    "v60",
                    "v70",
                    "v90",
                    "volvo (truck)",
                    "xc40",
                    "xc60",
                    "xc70",
                    "xc90",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $volvo_make->id, 'name' => ucfirst($model_name) ]);
        }

        //mercedes
        $mercedes_make = Make::where('name', 'LIKE', '%Mercedes%')->first();
        foreach ([
                    "a class",
                    "a class sedan",
                    "actros",
                    "arocs",
                    "atego",
                    "axor",
                    "b class",
                    "c class",
                    "c class stationwagon",
                    "citan 109",
                    "cl class",
                    "cla class",
                    "cla class shootingbrake",
                    "clk class",
                    "cls class",
                    "cls class shootingbrake",
                    "e class",
                    "e class stationwagon",
                    "g class",
                    "gelandewagen",
                    "gl class",
                    "gla class",
                    "glb class",
                    "glc class",
                    "gle class",
                    "glk class",
                    "gls class",
                    "gt class",
                    "m class",
                    "medium class",
                    "mercedes (truck)",
                    "r class",
                    "s class",
                    "sl class",
                    "slc class",
                    "slk class",
                    "sls amg",
                    "sprinter",
                    "v class",
                    "viano",
                    "vito",
                    "x class",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $mercedes_make->id, 'name' => ucfirst($model_name) ]);
        }

        //ford
        $ford_make = Make::where('name', 'LIKE', '%Ford%')->first();
        foreach ([
                    "bronco",
                    "ecosport",
                    "edge",
                    "escape",
                    "escort",
                    "everest",
                    "excursion",
                    "expedition",
                    "explorer",
                    "explorer sport trac",
                    "f150",
                    "festiva",
                    "ford",
                    "kuga",
                    "mondeo",
                    "mustang",
                    "ranger",
                    "s-max",
                    "taurus",
                    "thunderbird",
                    "transit",
                    "transit connect",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $ford_make->id, 'name' => ucfirst($model_name) ]);
        }

        //peugeot
        $peugeot_make = Make::create(['name' => 'Peugeot']);
        foreach ([
                    "1007",
                    "106",
                    "2008",
                    "206",
                    "207",
                    "208",
                    "3008",
                    "306",
                    "307",
                    "308",
                    "406",
                    "407",
                    "5008",
                    "508",
                    "e-2008",
                    "e-208",
                    "peugeot",
                    "rcz",
                    "rifter",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $peugeot_make->id, 'name' => ucfirst($model_name) ]);
        }

        //fiat
        $fiat_make = Make::create(['name' => 'Fiat']);
        foreach ([
                    "500",
                    "500c",
                    "500s",
                    "500x",
                    "barchetta",
                    "coupe fiat",
                    "fiat",
                    "grande punto",
                    "multipla",
                    "new barchetta",
                    "new multipla",
                    "new panda",
                    "panda",
                    "punto",
                    "punto evo",
                    "tipo",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $fiat_make->id, 'name' => ucfirst($model_name) ]);
        }

        //land_rover
        $land_rover_make = Make::where('name', 'LIKE', '%Land Rover%')->first();
        foreach ([
                    "defender",
                    "discovery",
                    "discovery 3",
                    "discovery 4",
                    "discovery sport",
                    "freelander",
                    "freelander 2",
                    "land rover range rover",
                    "lr4",
                    "range rover",
                    "range rover evoque",
                    "range rover evoque convertible",
                    "range rover evoque coupe",
                    "range rover sport",
                    "range rover velar",
                    "range rover vogue",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $land_rover_make->id, 'name' => ucfirst($model_name) ]);
        }

        //isuzu
        $isuzu_make = Make::where('name', 'LIKE', '%Isuzu%')->first();
        foreach ([
                    "117 coupe",
                    "aska",
                    "bighorn",
                    "d-max",
                    "elf truck",
                    "fargo",
                    "fargo truck",
                    "forward",
                    "forward juston",
                    "gemini",
                    "giga",
                    "isuzu",
                    "journey",
                    "juston",
                    "mu",
                    "mu wizard",
                    "mu-x",
                    "piazza",
                    "rodeo",
                    "vehicross",
                    "wizard",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $isuzu_make->id, 'name' => ucfirst($model_name) ]);
        }

        //lexus
        $lexus_make = Make::where('name', 'LIKE', '%Lexus%')->first();
        foreach ([
                    "ct",
                    "ct200h",
                    "es",
                    "es250",
                    "gs",
                    "gs f",
                    "gs250",
                    "gs300h",
                    "gs350",
                    "gs450h",
                    "gx460",
                    "gx470",
                    "hs",
                    "is",
                    "is f",
                    "is250c",
                    "is350",
                    "lc500",
                    "lexus",
                    "ls",
                    "ls430",
                    "ls460",
                    "lx",
                    "lx470",
                    "lx570",
                    "nx",
                    "nx200",
                    "nx200t",
                    "nx300",
                    "nx300h",
                    "rc",
                    "rc f",
                    "rx",
                    "rx200t",
                    "rx270",
                    "rx350",
                    "rx400h",
                    "sc430",
                    "ux",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $lexus_make->id, 'name' => ucfirst($model_name) ]);
        }

        //renault
        $renault_make = Make::create(['name' => 'Renault']);
        foreach ([
                    "5",
                    "alpine",
                    "alpine a110",
                    "avantime",
                    "captur",
                    "clio",
                    "kadjar",
                    "kangoo",
                    "kangoo bebop",
                    "koleos",
                    "lutecia",
                    "megane",
                    "megane estate",
                    "premium",
                    "renault",
                    "renault truck",
                    "twingo",
                    "wind",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $renault_make->id, 'name' => ucfirst($model_name) ]);
        }

        //porsche
        $porsche_make = Make::create(['name' => 'Porsche']);
        foreach ([
                    "718 boxster",
                    "718 cayman",
                    "911",
                    "boxster",
                    "cayenne",
                    "cayman",
                    "macan",
                    "panamera",
                    "porsche",
                    "taycan",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $porsche_make->id, 'name' => ucfirst($model_name) ]);
        }

        //citroen
        $citroen_make = Make::create(['name' => 'Citroen']);
        foreach ([
                    "berlingo",
                    "bx",
                    "c2",
                    "c3",
                    "c3 aircross",
                    "c3 pluriel",
                    "c4",
                    "c4 cactus",
                    "c4 picasso",
                    "c5",
                    "c5 aircross",
                    "c6",
                    "citroen",
                    "ds3",
                    "ds3 cabrio",
                    "ds3 crossback",
                    "ds4",
                    "ds5",
                    "grand c4 picasso",
                    "grand c4 spacetourer",
                    "xantia",
                    "xsara",
                    "xsara picasso",
                    "zx",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $citroen_make->id, 'name' => ucfirst($model_name) ]);
        }

        //alfa_romeo
        $alfa_romeo_make = Make::create(['name' => 'Alfa Romeo']);
        foreach ([
                    "4c",
                    "4c spider",
                    "alfa 145",
                    "alfa 147",
                    "alfa 155",
                    "alfa 156",
                    "alfa 159",
                    "alfa 159 sportwagon",
                    "alfa 164",
                    "alfa 166",
                    "alfa 75",
                    "alfa brera",
                    "alfa gt",
                    "alfa gtv",
                    "alfa spider",
                    "alfa sportwagon",
                    "giulia",
                    "giulietta",
                    "mito",
                    "stelvio",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $alfa_romeo_make->id, 'name' => ucfirst($model_name) ]);
        }

        //mini
        $mini_make = Make::create(['name' => 'Mini']);
        foreach ([
                    "cooper",
                    "mini",
                    "mini clubman",
                    "mini convertible",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $mini_make->id, 'name' => ucfirst($model_name) ]);
        }

        //jaguar
        $jaguar_make = Make::create(['name' => 'Jaguar']);
        foreach ([
                    "e pace",
                    "f pace",
                    "f type",
                    "i pace",
                    "jaguar",
                    "s type",
                    "sovereign",
                    "x type",
                    "xe",
                    "xf",
                    "xf sportbrake",
                    "xj",
                    "xjs",
                    "xk",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $jaguar_make->id, 'name' => ucfirst($model_name) ]);
        }

        //chrysler
        $chrysler_make = Make::create(['name' => 'Chrysler']);
        foreach ([
                    "cherokee",
                    "commander",
                    "compass",
                    "gladiator",
                    "grand cherokee",
                    "patriot",
                    "renegade",
                    "wrangler",
                    "wrangler unlimited",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $chrysler_make->id, 'name' => ucfirst($model_name) ]);
        }

        //bentley
        $bentley_make = Make::where('name', 'LIKE', '%Bentley%')->first();
        foreach ([
                    "arnage",
                    "bentayga",
                    "bentley",
                    "brooklands",
                    "continental",
                    "flying spur",
                    "mulsanne",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $bentley_make->id, 'name' => ucfirst($model_name) ]);
        }

        //aston_martin
        $aston_martin_make = Make::create(['name' => 'Aston Martin']);
        foreach ([
                    "db11",
                    "db9",
                    "dbs",
                    "dbx",
                    "rapide",
                    "v12 vanquish",
                    "v12 vantage",
                    "v8",
                    "vanquish",
                    "vantage",
                    "virage",
                 ] as $model_name) {
            CarModel::create([ 'make_id' => $aston_martin_make->id, 'name' => ucfirst($model_name) ]);
        }

        //hino
        $hino_make = Make::where('name', 'LIKE', '%HINO%')->first();
        foreach ([
                    "elise",
                    "evora",
                    "exige",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $hino_make->id, 'name' => ucfirst($model_name) ]);
        }

        //scania
        $scania_make = Make::where('name', 'LIKE', '%Scania%')->first();
        foreach ([
                    "tgm",
                    "tgs",
                    "tgx",
                 ] as $model_name) {
            CarModel::firstOrCreate([ 'make_id' => $scania_make->id, 'name' => ucfirst($model_name) ]);
        }
    }
}
